# Generated by Django 4.1.5 on 2023-01-21 18:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('gameId', models.AutoField(db_column='game_id', primary_key=True, serialize=False)),
                ('gameName', models.CharField(blank=True, db_column='game_name', default='', max_length=255, null=True)),
                ('gameActive', models.CharField(blank=True, db_column='game_active', default='1', max_length=1, null=True)),
                ('gameEntryId', models.IntegerField(db_column='game_entry_id', default=0)),
                ('gameEntryDate', models.DateField(db_column='game_entry_date', default=django.utils.timezone.now, editable=False)),
                ('gameModifiedId', models.IntegerField(db_column='game_modified_id', default=0)),
                ('gameModifiedDate', models.DateField(blank=True, db_column='game_modified_date', null=True)),
            ],
            options={
                'db_table': 'game',
                'managed': True,
            },
        ),
    ]
