# Generated by Django 4.1.5 on 2023-01-21 17:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('userId', models.AutoField(db_column='user_id', primary_key=True, serialize=False)),
                ('userName', models.CharField(blank=True, db_column='user_name', default='', max_length=255, null=True, unique=True)),
                ('userUpass', models.CharField(blank=True, db_column='user_upass', default='', max_length=64, null=True)),
                ('userAddress', models.CharField(blank=True, db_column='user_address', default='', max_length=100, null=True)),
                ('userMobile', models.CharField(blank=True, db_column='user_mobile', default='', max_length=18, null=True, unique=True)),
                ('userEmail', models.EmailField(blank=True, db_column='user_email', default='', max_length=100, null=True, unique=True)),
                ('userRoleId', models.IntegerField(blank=True, db_column='user_role_id', default=0, null=True)),
                ('userActive', models.CharField(blank=True, db_column='user_active', default='1', max_length=1, null=True)),
                ('userEntryId', models.IntegerField(blank=True, db_column='user_entry_id', default=0, null=True)),
                ('userEntryDate', models.DateTimeField(blank=True, db_column='user_entry_date', default=django.utils.timezone.now, null=True)),
                ('userModifiedId', models.IntegerField(blank=True, db_column='user_modified_id', default=0, null=True)),
                ('userModifiedDate', models.DateTimeField(blank=True, db_column='user_modified_date', null=True)),
            ],
            options={
                'db_table': 'user',
                'managed': True,
            },
        ),
    ]
