# Generated by Django 4.1.5 on 2023-01-21 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_user_userentrydate_alter_user_usermodifieddate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='userModifiedDate',
            field=models.DateField(blank=True, db_column='user_modified_date', null=True),
        ),
    ]
